### ISSUE TITLE
Lines may not behave as you expect when import this file

### ISSUE THREAD

**Issue by dacb** [StevenJYWu/TYPER#6]
https://github.com/sborje/TYPER/blob/4807874e3ac8903e30074391a734c560439946c7/TYPEr/getPMID_Abstracts.py#L87

**Comment by dacb** [comment]
Because they are outside of functions you have minimal control of when these lines run.

**Comment by StevenJYWu** [comment]
Issue Resolved.
We merged the separately written .py files together into one cohesive script. It has an argparser incorporated in the script. README will be updated with information on it shortly.
